version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build: .
    command: gunicorn trippin.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgis/postgis:15-3.3
    volumes:
      - postgis_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=travelplanner
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
volumes:
  postgis_data:
  static_volume: