# Generated by Django 5.0.10 on 2025-02-09 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('ATTRACTION', 'Tourist Attraction'), ('RESTAURANT', 'Restaurant'), ('MUSEUM', 'Museum'), ('OUTDOOR', 'Outdoor Activity'), ('SHOPPING', 'Shopping'), ('ENTERTAINMENT', 'Entertainment')], max_length=20)),
                ('google_place_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('price_level', models.IntegerField(null=True)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trip.location')),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_reference', models.CharField(max_length=500)),
                ('photo_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='activities.activity')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type'], name='activities__activit_8e7970_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['google_place_id'], name='activities__google__8c0821_idx'),
        ),
    ]
