# Generated by Django 4.2.17 on 2024-12-30 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
