# Generated by Django 5.0.10 on 2025-02-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover image for the trip', null=True, upload_to='trip_images/'),
        ),
    ]
