# Generated by Django 5.0.10 on 2025-02-09 17:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('VISA', 'Visa'), ('ID_CARD', 'ID Card'), ('INSURANCE', 'Insurance'), ('VACCINATION', 'Vaccination Certificate'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='documents/user/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'), models.Index(fields=['expiry_date'], name='documents_d_expiry__1d702a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TripDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('BOOKING', 'Booking Confirmation'), ('TICKET', 'Ticket'), ('ITINERARY', 'Itinerary'), ('RESERVATION', 'Reservation'), ('OTHER', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='documents/trips/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='trip.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type'], name='documents_t_documen_7f498d_idx')],
            },
        ),
    ]
